<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Body">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Execute">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="requestParameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="Operator"/>
                    <xs:element type="xs:byte" name="SerialNo"/>
                    <xs:element type="xs:byte" name="MaterialCode"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>