<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Execute" type="tem:ExecuteType" xmlns:tem="http://tempuri.org/"/>
  <xs:complexType name="requestParametersType">
    <xs:sequence>
      <xs:element type="xs:string" name="Mode"/>
      <xs:element type="xs:string" name="Operator"/>
      <xs:element type="xs:string" name="SerialNo"/>
      <xs:element type="xs:string" name="HuNo"/>
      <xs:element type="xs:string" name="MaterialCode"/>
      <xs:element type="xs:string" name="PackingInstructions"/>
      <xs:element type="xs:string" name="ProductionVersion"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ExecuteType">
    <xs:sequence>
      <xs:element type="tem:requestParametersType" name="requestParameters" xmlns:tem="http://tempuri.org/"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>