<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="soap:Envelope">
    <xs:complexType>
      <xs:sequence>
		  <xs:element name="soap:Body">
		  <xs:complexType>
			<xs:sequence>
				<xs:element name="Execute">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="requestParameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Mode" type="xs:string"/>
										<xs:element name="Operator" type="xs:string"/>
										<xs:element name="SerialNo" type="xs:string"/>
										<xs:element name="HuNo" type="xs:string"/>
										<xs:element name="MaterialCode" type="xs:string"/>
										<xs:element name="PackingInstructions" type="xs:string"/>
										<xs:element name="ProductionVersion" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					  </xs:complexType>
				  </xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>